language: erlang
otp_release:
  - 18.0
  - 19.1
matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9
      addons:
        apt:
          packages:
            - g++-4.9
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
